// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Slider, GroupBox, HorizontalBox, VerticalBox, GridBox } from "std-widgets.slint";

export component App inherits Window {
    // 避免双向绑定
    in property <image> texture;
    out property <int> requested-texture-width: i-image.width/1phx;
    out property <int> requested-texture-height: i-image.height/1phx;
    
    // 使用私有属性存储当前旋转状态
    private property <float> current-x: 0;
    private property <float> current-y: 0;
    out property <float> rotation-x: current-x;
    out property <float> rotation-y: current-y;

    // 存储拖动开始时的旋转角度
    private property <float> start-x;
    private property <float> start-y;

    preferred-width: 800px;
    preferred-height: 600px;
    title: "Point Cloud Viewer";

    touch-area := TouchArea {
        width: 100%;
        height: 100%;
        
        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                root.start-x = root.current-x;
                root.start-y = root.current-y;
            } else if (event.kind == PointerEventKind.move && self.pressed) {
                root.current-x = root.start-x + (self.mouse-y - self.pressed-y) / 1px;
                root.current-y = root.start-y + (self.mouse-x - self.pressed-x) / 1px * 0.5;
            }
        }

        i-image := Image {
            source: root.texture;
            width: 100%;
            height: 100%;
        }
    }
}
